In [23]:
import numpy as np

arr1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr1)
print(type(arr1))
print(arr1.shape)
arr1.reshape(5,2)

[[1 2 3 4 5]
 [2 3 4 5 6]]
<class 'numpy.ndarray'>
(2, 5)


array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
print(arr1)
print(arr1.dtype)
print(arr1.size)
print(arr1.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
int64
10
(2, 5)


In [37]:
# Vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,4,5,6])
print(arr1+arr2)

# Substraction
print(arr2-arr1)

print(arr1*arr2)

print(arr1/arr2)

print(arr1**2)

print(arr1>2)

print(arr1[1:4])

[ 3  5  7  9 11]
[1 1 1 1 1]
[ 2  6 12 20 30]
[0.5        0.66666667 0.75       0.8        0.83333333]
[ 1  4  9 16 25]
[False False  True  True  True]
[2 3 4]


In [43]:
# Universal Functions
arr=np.array([1,2,3,4,5])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sign(arr))

print(np.log(arr))

print(np.log10(arr))

print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[1 1 1 1 1]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [66]:
# Array Slicing and Indexing
arr=np.array([[1,2,3,4,5],[1,2,3,3,4],[1,2,3,4,5]])

print(arr[0][0])

print(arr[0,0])

print(arr[1:3,2:])


1
1
[[3 3 4]
 [3 4 5]]


In [71]:
# Normalization

data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)

print(arr)

normalize_data = (data-mean)/std_dev
print(normalize_data)


[1 2 3 4 5]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [82]:
mean=np.mean(data)
std_dev=np.std(data)
variance=np.var(data)

# Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>3) & (data<7)]


array([4, 5, 6])